// ======= Page Owner Vikash =========
// ======= Data for Transport Table =========
const rows = [
  {
    id: 1,
    AdmNo: '8574',
    Section: 'A',
    StudentName: 'Pawan',
    class: 'X',
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 2,
    AdmNo: '8575',
    Section: 'B',
    StudentName: 'John',
    class: 'V',
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 3,
    AdmNo: '8576',
    Section: 'C',
    StudentName: 'Jane',
    class: 'I',
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
  {
    id: 4,
    AdmNo: '8577',
    Section: 'A',
    StudentName: 'Alice',
    class: 'VI',
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 5,
    AdmNo: '8578',
    Section: 'B',
    StudentName: 'Bob',
    class: 'XI',
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 6,
    AdmNo: '8579',
    Section: 'C',
    StudentName: 'Emily',
    class: 'IX',
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
  {
    id: 7,
    AdmNo: '8580',
    Section: 'A',
    StudentName: 'Michael',
    class: 'X',
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 8,
    AdmNo: '8581',
    Section: 'B',
    StudentName: 'Sara',
    class: 'III',
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 9,
    AdmNo: '8582',
    Section: 'C',
    StudentName: 'David',
    class: 'V',
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
  {
    id: 10,
    AdmNo: '8583',
    Section: 'A',
    StudentName: 'Jessica',
    class: 'II',
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 11,
    AdmNo: '8584',
    Section: 'B',
    StudentName: 'Peter',
    class: 'IV',
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 12,
    AdmNo: '8585',
    Section: 'C',
    StudentName: 'Sophia',
    class: 'XII',
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
  {
    id: 13,
    AdmNo: '8586',
    Section: 'A',
    StudentName: 'Daniel',
    class: 'X',
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 14,
    AdmNo: '8587',
    Section: 'B',
    StudentName: 'Olivia',
    class: 'VII',
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 15,
    AdmNo: '8588',
    Section: 'C',
    StudentName: 'William',
    class: 'VIII',
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  }
];

export default rows;
