const rows = [
  {
    id: 1,
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 2,
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 3,
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
  {
    id: 4,
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 5,
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 6,
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
  {
    id: 7,
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 8,
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 9,
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
  {
    id: 10,
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 11,
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 12,
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
  {
    id: 13,
    EffectFrom: '03-05-2000',
    PickRoute: 'Route 1',
    DropRoute: 'Route 10',
    TransportMonths: 'Apr`24, May`24, Jun`24',
    FeeSlab: 'Slab 1',
    PickStop: 'Stop 1',
    DropStop: 'Stop 2',
    TransportLeftDate: '01-May-2024',
    Remarks: 'Good Service'
  },
  {
    id: 14,
    EffectFrom: '10-12-2001',
    PickRoute: 'Route 2',
    DropRoute: 'Route 5',
    TransportMonths: 'Jun`24, Jul`24, Aug`24',
    FeeSlab: 'Slab 2',
    PickStop: 'Stop 3',
    DropStop: 'Stop 4',
    TransportLeftDate: '15-Apr-2024',
    Remarks: 'Average Service'
  },
  {
    id: 15,
    EffectFrom: '15-09-2002',
    PickRoute: 'Route 3',
    DropRoute: 'Route 7',
    TransportMonths: 'Aug`24, Sep`24, Oct`24',
    FeeSlab: 'Slab 3',
    PickStop: 'Stop 5',
    DropStop: 'Stop 6',
    TransportLeftDate: '20-Jun-2024',
    Remarks: 'Excellent Service'
  },
];

export default rows;
