const RouteData = [
    {
      id: 1,
      routeName: 'Route 1',
      status: 'Active',
      schedule: 'One Time',
      pickstarttime: '10 AM',
      pickendtime: '4 PM',
      dropstarttime: '10 AM',
      dropendtime: '4 PM',
      attachBus: 'Bus 1',
      seatingCapacity: 10,
      attachSlab: 'Slab 1',
      classes: 'X, III, V, I'
    },
    {
      id: 2,
      routeName: 'Route 2',
      status: 'Inactive',
      schedule: 'Daily',
      pickstarttime: '8 AM',
      pickendtime: '3 PM',
      dropstarttime: '8 AM',
      dropendtime: '3 PM',
      attachBus: 'Bus 2',
      seatingCapacity: 15,
      attachSlab: 'Slab 2',
      classes: 'IX, VII, II, VI'
    },
    {
      id: 3,
      routeName: 'Route 3',
      status: 'Active',
      schedule: 'Weekly',
      pickstarttime: '9 AM',
      pickendtime: '5 PM',
      dropstarttime: '9 AM',
      dropendtime: '5 PM',
      attachBus: 'Bus 3',
      seatingCapacity: 20,
      attachSlab: 'Slab 3',
      classes: 'XII, XI, VIII, IV'
    },
    {
      id: 4,
      routeName: 'Route 4',
      status: 'Active',
      schedule: 'One Time',
      pickstarttime: '11 AM',
      pickendtime: '3 PM',
      dropstarttime: '11 AM',
      dropendtime: '3 PM',
      attachBus: 'Bus 4',
      seatingCapacity: 12,
      attachSlab: 'Slab 4',
      classes: 'VI, IV, III, II'
    },
    {
      id: 5,
      routeName: 'Route 5',
      status: 'Active',
      schedule: 'Daily',
      pickstarttime: '9 AM',
      pickendtime: '4 PM',
      dropstarttime: '9 AM',
      dropendtime: '4 PM',
      attachBus: 'Bus 5',
      seatingCapacity: 18,
      attachSlab: 'Slab 5',
      classes: 'VII, IX, XI, X'
    },
    {
      id: 6,
      routeName: 'Route 6',
      status: 'Inactive',
      schedule: 'Weekly',
      pickstarttime: '10 AM',
      pickendtime: '5 PM',
      dropstarttime: '10 AM',
      dropendtime: '5 PM',
      attachBus: 'Bus 6',
      seatingCapacity: 16,
      attachSlab: 'Slab 6',
      classes: 'IV, VI, X, XII'
    },
    {
      id: 7,
      routeName: 'Route 7',
      status: 'Active',
      schedule: 'One Time',
      pickstarttime: '9 AM',
      pickendtime: '2 PM',
      dropstarttime: '9 AM',
      dropendtime: '2 PM',
      attachBus: 'Bus 7',
      seatingCapacity: 14,
      attachSlab: 'Slab 7',
      classes: 'I, II, III, IV'
    },
    {
      id: 8,
      routeName: 'Route 8',
      status: 'Active',
      schedule: 'Daily',
      pickstarttime: '7 AM',
      pickendtime: '4 PM',
      dropstarttime: '7 AM',
      dropendtime: '4 PM',
      attachBus: 'Bus 8',
      seatingCapacity: 20,
      attachSlab: 'Slab 8',
      classes: 'IX, X, XI, XII'
    },
    {
      id: 9,
      routeName: 'Route 9',
      status: 'Active',
      schedule: 'Weekly',
      pickstarttime: '8 AM',
      pickendtime: '3 PM',
      dropstarttime: '8 AM',
      dropendtime: '3 PM',
      attachBus: 'Bus 9',
      seatingCapacity: 22,
      attachSlab: 'Slab 9',
      classes: 'V, VI, VII, VIII'
    },
    {
      id: 10,
      routeName: 'Route 10',
      status: 'Inactive',
      schedule: 'One Time',
      pickstarttime: '10 AM',
      pickendtime: '5 PM',
      dropstarttime: '10 AM',
      dropendtime: '5 PM',
      attachBus: 'Bus 10',
      seatingCapacity: 15,
      attachSlab: 'Slab 10',
      classes: 'X, XI, XII, IX'
    },
  ];
  
  export default RouteData;
  