

export const data = [
  { id: 1, sub: 'E', name: 'ENGLISH', description: 'Description for Item 1', dueDate: '12-05-2024', date: '10-01-2023', attachmentNo: 2, homework: "disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },
  { id: 2, sub: 'H', name: 'HINDI', description: 'Description for Item 2', dueDate: '12-01-2023', date: '9-01-2023', attachmentNo: 3, homework: "disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },
  { id: 3, sub: 'M', name: 'MATH', description: 'Description for Item 3', dueDate: '12-01-2023', date: '5-01-2023', attachmentNo: 4, homework: "disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },
  { id: 4, sub: 'M', name: 'MATH', description: 'Description for Item 3', dueDate: '12-01-2023', date: '10-01-2023', attachmentNo: 2, homework: "disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },
  { id: 5, sub: 'M', name: 'English', description: 'Description for Item 3', dueDate: '12-01-2023', date: '10-01-2023', attachmentNo: 3, homework: "disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },
  { id: 6, sub: 'M', name: 'MATH', description: 'Description for Item 3', dueDate: '12-01-2023', date: '10-01-2023', attachmentNo: 4, homework: "disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },
  { id: 7, sub: 'E', name: 'ENGLISH', description: 'Description for Item 3', dueDate: '12-01-2023', date: '10-01-2023', attachmentNo: 3, homework: "disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },
  { id: 8, sub: 'E', name: 'ENGLISH', description: 'Description for Item 3', dueDate: '12-01-2023', date: '10-01-2023', attachmentNo: 5, homework: "disinformation)disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1 presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },

  { id: 9, sub: 'E', name: 'ENGLISH', description: 'Description for Item 3', dueDate: '12-01-2023', date: '10-01-2023', attachmentNo: 2, homework: "disinformation)disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1 presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },

  { id: 10, sub: 'E', name: 'ENGLISH', description: 'Description for Item 3', dueDate: '12-01-2023', date: '10-01-2023', attachmentNo: 6, homework: "disinformation)disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1 presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" },

  { id: 11, sub: 'E', name: 'ENGLISH', description: 'Description for Item 3', dueDate: '12-01-2023', date: '10-01-2023', attachmentNo: 2, homework: "disinformation)disinformation) presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1 presented as news. Fake news often has the aim of damaging the reputation of a person or entity, or making money through advertising revenue.[1][2] Although false news has always been spread throughout history, the term  was first used in the 1890s when" }
];
