const RouteData = [
    {
      id: 1,
      VisitorName: 'Rahul Sharma',
      avatarUrl:'https://i.pravatar.cc/150?img=4',
      altName:"Remy Sharp",
      status:'Expected',
      Accompaniedby:3,
      Purpose:'Submission',
      EntryDate: '09-Feb-2021',
      GatePass:'Gate Pass 1',
      Phone: 8954452658,
      TimeIn: '10 AM',
      TimeOut: '4 PM',
      Address: 'H no 486 Dhakoli',
      ToMeet: 'Mohit',

    },
    {
        id: 2,
        VisitorName: 'John Deo',
        avatarUrl:'https://i.pravatar.cc/150?img=7',
        status:'Checked In',
        Accompaniedby:1,
        Purpose:'Submission',
        EntryDate: '11-Dec-2020',
        GatePass:'Gate Pass 1',
        Phone: 9865488956,
        TimeIn: '11 AM',
        TimeOut: '1 PM',
        Address: 'Flatno 5 Zirakpur',
        ToMeet: 'Tarun'
    },
    {   id: 3,
        VisitorName: 'Manuel',
        avatarUrl:'https://i.pravatar.cc/150?img=8',
        status:'Checked Out',
        Accompaniedby:2,
        Purpose:'Submission',
        EntryDate: '15-Mar-2024',
        GatePass:'Gate Pass 1',
        Phone: 9845649894,
        TimeIn: '12 AM',
        TimeOut: '1 PM',
        Address: '9133 Lakeview St',
        ToMeet: 'Sylvia Mcdonalid'
    },
    {
        id: 4,
        VisitorName: 'Clinton ',
        avatarUrl:'https://i.pravatar.cc/150?img=9',
        status:'Do Not Admit',
        Accompaniedby:2,
        Purpose:'Submission',
        EntryDate: '04-Jan-2024',
        GatePass:'Gate Pass 1',
        Phone: 9548485785,
        TimeIn: '9 AM',
        TimeOut: '11 AM',
        Address: '8160 Washington Ave',
        ToMeet: 'Alan Ryan'
    },
    {
        id: 5,
        VisitorName: 'Marc ',
        avatarUrl:'https://i.pravatar.cc/150?img=10',
        status:'Do Not Admit',
        Accompaniedby:1,
        Purpose:'Submission',
        EntryDate: '09-Mar-2022',
        GatePass:'Gate Pass 1',
        Phone: 9896464167,
        TimeIn: '7 AM',
        TimeOut: '11 AM',
        Address: '9734 Paddock Way',
        ToMeet: 'Tristan Silva'
    },
    {
        id:6,
        VisitorName: 'Anthony',
        avatarUrl:'https://i.pravatar.cc/150?img=11',
        status:'Pending',
        Accompaniedby:2,
        Purpose:'Submission',
        EntryDate: '20-Mar-2024',
        GatePass:'Gate Pass 1',
        Phone: 7841465485,
        TimeIn: '2 PM',
        TimeOut: '4 PM',
        Address: '8371 Depaul Dr',
        ToMeet: 'Martin Robinson'
    },
    {
        id: 7,
        VisitorName: 'Ross Sims',
        avatarUrl:'https://i.pravatar.cc/150?img=12',
        status:'Expected',
        Accompaniedby:2,
        Purpose:'Submission',
        EntryDate: '15-Dec-2024',
        GatePass:'Gate Pass 1',
        Phone: 9655984658,
        TimeIn: '11 AM',
        TimeOut: '2 PM',
        Address: '1020 Bruce St',
        ToMeet: 'Marsha Ortiz'
    },
    {
        id: 8,
        VisitorName: 'Aaron',
        avatarUrl:'https://i.pravatar.cc/150?img=13',
        status:'Checked In',
        Accompaniedby:1,
        Purpose:'Submission',
        EntryDate: '30-Sep-2024',
        GatePass:'Gate Pass 1',
        Phone: 7568965489,
        TimeIn: '11 AM',
        TimeOut: '12 PM',
        Address: '4877 Daisy Dr',
        ToMeet: 'Noelle Barnett'
    },
    {
        id: 9,
        VisitorName: 'Naomi',
        avatarUrl:'https://i.pravatar.cc/150?img=14',
        status:'Checked In',
        Accompaniedby:3,
        Purpose:'Submission',
        EntryDate: '24-Oct-2024',
        GatePass:'Gate Pass 1',
        Phone: 8456932127,
        TimeIn: '3 PM',
        TimeOut: '4 PM',
        Address: '2001 Mockingbird Hill',
        ToMeet: 'Jackson Banks'
    },
    {
        id: 10,
        VisitorName: 'Camila',
        avatarUrl:'https://i.pravatar.cc/150?img=15',
        status:'Checked Out',
        Accompaniedby:2,
        Purpose:'Submission',
        EntryDate: '12-Aug-2024',
        GatePass:'Gate Pass 1',
        Phone: 9314526587,
        TimeIn: '7 AM',
        TimeOut: '2 PM',
        Address: '1645 Parker Rd',
        ToMeet: 'Salvador Rivera'
    },
  ];
  
  export default RouteData;
  