export const StudentList = [
  { id: 1, value:'1', admnNo: 'ADM001', name: 'Emma Johnson', gender:'male', class: 'Class IX', section: 'A' },
  { id: 2, value:'2', admnNo: 'ADM002', name: 'Liam Smith', gender:'female', class: 'Class X', section: 'B' },
  { id: 3, value:'3', admnNo: 'ADM003', name: 'Olivia Davis', gender:'male', class: 'Class VIII', section: 'C' },
  { id: 4, value:'4', admnNo: 'ADM004', name: 'Noah Brown', gender:'female', class: 'Class VII', section: 'A' },
  { id: 5, value:'5', admnNo: 'ADM005', name: 'Ava Wilson', gender:'male', class: 'Class VI', section: 'B' },
  { id: 6, value:'6', admnNo: 'ADM006', name: 'Sophia Moore', gender:'male', class: 'Class IX', section: 'C' },
  { id: 7, value:'7', admnNo: 'ADM007', name: 'Jackson Anderson', gender:'female', class: 'Class X', section: 'A' },
  { id: 8, value:'8', admnNo: 'ADM008', name: 'Isabella Taylor', gender:'male', class: 'Class VIII', section: 'B' },
  { id: 9, value:'9', admnNo: 'ADM009', name: 'Lucas Harris', gender:'female', class: 'Class VII', section: 'C' },
  { id: 10, value:'10', admnNo: 'ADM010', name: 'Amelia Martin', gender:'male', class: 'Class VI', section: 'A' },
  { id: 11, value:'11', admnNo: 'ADM011', name: 'Oliver White', gender:'female', class: 'Class IX', section: 'B' },
  { id: 12, value:'12', admnNo: 'ADM012', name: 'Emma Johnson', gender:'male', class: 'Class X', section: 'C' },
  { id: 13, value:'13', admnNo: 'ADM013', name: 'Elijah Thompson', gender:'male', class: 'Class VIII', section: 'A' },
  { id: 14, value:'14', admnNo: 'ADM014', name: 'Ava Garcia', gender:'female', class: 'Class VII', section: 'B' },
  { id: 15, value:'15', admnNo: 'ADM015', name: 'Mia Clark', gender:'male', class: 'Class VI', section: 'C' },
  { id: 16, value:'16', admnNo: 'ADM016', name: 'Carter Lee', gender:'female', class: 'Class IX', section: 'A' },
  { id: 17, value:'17', admnNo: 'ADM017', name: 'Scarlett Rodriguez', gender:'female', class: 'Class X', section: 'B' },
  { id: 18, value:'18', admnNo: 'ADM018', name: 'Leo Wright', gender:'male', class: 'Class VIII', section: 'C' },
  { id: 19, value:'19', admnNo: 'ADM019', name: 'Chloe Hall', gender:'male', class: 'Class VII', section: 'A' },
  { id: 20, value:'20', admnNo: 'ADM020', name: 'Ethan Lewis', gender:'male', class: 'Class VI', section: 'B' },
  { id: 21, value:'21', admnNo: 'ADM021', name: 'Luna Foster', gender:'female', class: 'Class IX', section: 'C' },
  { id: 22, value:'22', admnNo: 'ADM022', name: 'Mason Turner', gender:'male', class: 'Class X', section: 'A' },
  { id: 23, value:'23', admnNo: 'ADM023', name: 'Lily Murphy', gender:'female', class: 'Class VIII', section: 'B' },
  { id: 24, value:'24', admnNo: 'ADM024', name: 'Alexander Bell', gender:'male', class: 'Class VII', section: 'C' },
  { id: 25, value:'25', admnNo: 'ADM025', name: 'Grace Cooper', gender:'male', class: 'Class VI', section: 'A' },
];
