export const StudentList = [
    { id: 1, name: 'Emma Johnson', class: 'Class IX', section: 'A' },
    { id: 2, name: 'Liam Smith', class: 'Class X', section: 'B' },
    { id: 3, name: 'Olivia Davis', class: 'Class VIII', section: 'C' },
    { id: 4, name: 'Noah Brown', class: 'Class VII', section: 'A' },
    { id: 5, name: 'Ava Wilson', class: 'Class VI', section: 'B' },
    { id: 6, name: 'Sophia Moore', class: 'Class IX', section: 'C' },
    { id: 7, name: 'Jackson Anderson', class: 'Class X', section: 'A' },
    { id: 8, name: 'Isabella Taylor', class: 'Class VIII', section: 'B' },
    { id: 9, name: 'Lucas Harris', class: 'Class VII', section: 'C' },
    { id: 10, name: 'Amelia Martin', class: 'Class VI', section: 'A' },
    { id: 11, name: 'Oliver White', class: 'Class IX', section: 'B' },
    { id: 12, name: 'Emma Johnson', class: 'Class X', section: 'C' },
    { id: 13, name: 'Elijah Thompson', class: 'Class VIII', section: 'A' },
    { id: 14, name: 'Ava Garcia', class: 'Class VII', section: 'B' },
    { id: 15, name: 'Mia Clark', class: 'Class VI', section: 'C' },
    { id: 16, name: 'Carter Lee', class: 'Class IX', section: 'A' },
    { id: 17, name: 'Scarlett Rodriguez', class: 'Class X', section: 'B' },
    { id: 18, name: 'Leo Wright', class: 'Class VIII', section: 'C' },
    { id: 19, name: 'Chloe Hall', class: 'Class VII', section: 'A' },
    { id: 20, name: 'Ethan Lewis', class: 'Class VI', section: 'B' },
    { id: 21, name: 'Luna Foster', class: 'Class IX', section: 'C' },
    { id: 22, name: 'Mason Turner', class: 'Class X', section: 'A' },
    { id: 23, name: 'Lily Murphy', class: 'Class VIII', section: 'B' },
    { id: 24, name: 'Alexander Bell', class: 'Class VII', section: 'C' },
    { id: 25, name: 'Grace Cooper', class: 'Class VI', section: 'A' },
  ];
  