import {
    randomTraderName,
    randomCity,
    randomJobTitle,
    randomPhoneNumber,
    randomId,
    randomDesk
  } from '@mui/x-data-grid-generator';

export const initialRows = [
    {
      id:randomId(),
      emp: randomTraderName(),
      D_O_J:'21-05-2005',
      Loc: randomCity(),
      Dept:randomDesk(),
      post: randomJobTitle(),
      phn: randomPhoneNumber(),
      'reporting-manager':randomTraderName(),
    },
    {
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),
      },
      { 
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),
      },
      { 
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),

      },
      {
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),
      },
      {
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),
      },
      {
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),
      },
      {
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),
      },
      {
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),
      },
      {
        id:randomId(),
        emp: randomTraderName(),
        D_O_J:'21-05-2005',
        Loc: randomCity(),
        Dept:randomDesk(),
        post: randomJobTitle(),
        phn: randomPhoneNumber(),
        'reporting-manager':randomTraderName(),
      },
  ];
  